"""Initial migration

Revision ID: 2000697c5e55
Revises: 
Create Date: 2025-08-09 05:50:57.567515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2000697c5e55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stamp',
    sa.Column('stamp_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('stamp_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('X', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_stamp',
    sa.Column('user_stamp_id', sa.Integer(), nullable=False),
    sa.Column('after_stamp', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('stamp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['stamp_id'], ['stamp.stamp_id'], ),
    sa.PrimaryKeyConstraint('user_stamp_id')
    )
    op.create_table('water_record',
    sa.Column('water_id', sa.Integer(), nullable=False),
    sa.Column('water_date', sa.DateTime(), nullable=False),
    sa.Column('water_type', sa.String(length=50), nullable=True),
    sa.Column('water_amount', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('water_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_record')
    op.drop_table('user_stamp')
    op.drop_table('users')
    op.drop_table('stamp')
    # ### end Alembic commands ###
